### PR TITLE
Make `respond_to?` compatible with default behavior

### LINKED ISSUE #104: IRB crash
## Describe the bug

Hello.
Using dry-logic 1.4.0, irb 1.5.0.

As I mentioned in https://github.com/ruby/irb/issues/455, a session crashes if irb's autocomplete feature is enabled.

## To Reproduce

Type `AnyClass.new.` in console.
Other details in irb issue link.

## Expected behavior

No session crash.

### PR DESCRIPTION
**Pull request by solnic**
Fixes #104 
Refs #99 
Refs #95 
Refs #73

### CODE REVIEW

File: lib/dry/logic/predicates.rb [hunk 1]
```diff
@@ -254,8 +254,13 @@ def uri_rfc3986?(input)
           format?(URI::RFC3986_Parser::RFC3986_URI, input)
         end
 
-        def respond_to?(method, input)
-          input.respond_to?(method)
+        def respond_to?(*args)
```
Comment (timriley) [inline lib/dry/logic/predicates.rb:257]: Probably worth a comment above this explaining how we're delegating back to Object's `respond_to?` for compatibility reasons?

**Review by timriley — APPROVED** [review]
Clever fix!

File: lib/dry/logic/predicates.rb (hunk 1 above)
Comment (flash-gordon) [inline lib/dry/logic/predicates.rb:257]: `*args` allocated an array, I think you can achieve the same semantics with `respond_to?(m, input = Undefined)`. I prefer to avoid using `*` and `**` when possible for this reason.
